# Generated by Django 4.2.1 on 2023-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='attached_file',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
