# Generated by Django 4.2.1 on 2023-05-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
